// <auto-generated />
using LaunchApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LaunchApi.Migrations
{
    [DbContext(typeof(LaunchApiContext))]
    [Migration("20220824224334_intital")]
    partial class intital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LaunchApi.Models.Launch", b =>
                {
                    b.Property<int>("LaunchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DaysToLaunch")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Mission")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("LaunchId");

                    b.ToTable("Launches");

                    b.HasData(
                        new
                        {
                            LaunchId = 1,
                            DaysToLaunch = 5,
                            Location = "Kennedy Space Center",
                            Mission = "Artemis"
                        },
                        new
                        {
                            LaunchId = 2,
                            DaysToLaunch = 6,
                            Location = "Vandenberg SFB",
                            Mission = "Starlink-58 (3-4)"
                        },
                        new
                        {
                            LaunchId = 3,
                            DaysToLaunch = 11,
                            Location = "Cape Canaveral",
                            Mission = "Starlink-59(4-20)"
                        },
                        new
                        {
                            LaunchId = 4,
                            DaysToLaunch = 13,
                            Location = "Guiana Space Centre",
                            Mission = "Eutelsat Konnect VHTS"
                        },
                        new
                        {
                            LaunchId = 5,
                            DaysToLaunch = 13,
                            Location = "Pacific Spaceport Complex - A",
                            Mission = "RS1 Flight 1"
                        },
                        new
                        {
                            LaunchId = 6,
                            DaysToLaunch = 14,
                            Location = "Kennedy Space Center",
                            Mission = "Starlink (4-2)"
                        },
                        new
                        {
                            LaunchId = 7,
                            DaysToLaunch = 18,
                            Location = "Vandenberg SFB",
                            Mission = "To the Black"
                        },
                        new
                        {
                            LaunchId = 8,
                            DaysToLaunch = 29,
                            Location = "Baikonur Cosmodrome",
                            Mission = "Soyuz MS-22"
                        },
                        new
                        {
                            LaunchId = 9,
                            DaysToLaunch = 32,
                            Location = "Vandenberg SFB",
                            Mission = "NROL-91"
                        },
                        new
                        {
                            LaunchId = 10,
                            DaysToLaunch = 30,
                            Location = "Rocket Lab Launch Complex",
                            Mission = "The Owl Spreads Its Wings"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
